name: daf
channels:
- conda-forge
dependencies:
- python=3.6
- psychopy
- ipython
- pip
- pip:
  - pyo
  - pyparallel; platform_system != "Windows"
  - SoundFile; platform_system == "Windows"
  - websocket_client
  - pyserial
  - pynput
